version: "2.4"

services:
  build-simulator:
    build: .
    image: ${SIMULATOR_DOCKER_IMAGE}:2019.3.15f1
    user: ${UID}
    environment:
      - S3_DOWNLOAD_HOST
      - SIM_ENVIRONMENTS
      - SIM_VEHICLES
      - SIMULATOR_CONTROLLABLES
      - SIM_SENSORS
      - SIMULATOR_NPCS
      - CLOUD_URL
      - JENKINS_BUILD_ID
      - GIT_COMMIT
      - GIT_BRANCH
      - GIT_TAG
      - UNITY_USERNAME
      - UNITY_PASSWORD
      - UNITY_SERIAL
      - CODE_SIGNING_PASSWORD
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - ..:/mnt
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/tmp/.Xauthority
      - ${CODE_SIGNING_FILE}:/tmp/signing.p12
    runtime: "nvidia"
    privileged: true
    entrypoint: "/mnt/Jenkins/build-simulator.sh"

  build-bundles:
    build: .
    image: ${SIMULATOR_DOCKER_IMAGE}:2019.3.15f1
    user: ${UID}
    environment:
      - SIM_ENVIRONMENTS
      - SIM_VEHICLES
      - JENKINS_BUILD_ID
      - GIT_COMMIT
      - GIT_BRANCH
      - GIT_TAG
      - UNITY_USERNAME
      - UNITY_PASSWORD
      - UNITY_SERIAL
      - DISPLAY
      - XAUTHORITY=/tmp/.Xauthority
    volumes:
      - ..:/mnt
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/tmp/.Xauthority
    runtime: "nvidia"
    privileged: true
    entrypoint: "/mnt/Jenkins/build-bundles.sh"

  upload-bundles:
    image: mesosphere/aws-cli
    user: ${UID}
    environment:
      - SIM_ENVIRONMENTS
      - SIM_VEHICLES
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_BUCKET_NAME
      - GIT_COMMIT
    volumes:
      - ..:/mnt
      - /etc/localtime:/etc/localtime:ro
    entrypoint: "/mnt/Jenkins/upload-bundles.sh"

  upload-bundles-wise:
    image: auto-gitlab.lgsvl.net:4567/hdrp/wise-cli
    user: ${UID}
    environment:
      - SIM_ENVIRONMENTS
      - SIM_VEHICLES
      - WISE_USERNAME
      - WISE_PASSWORD
      - WISE_URL
      - HOME=/tmp
    volumes:
      - ..:/mnt
      - /etc/localtime:/etc/localtime:ro
    entrypoint: "/mnt/Jenkins/upload-bundles-wise.sh"
